/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yyty_hao_studyproject_jni_JniTest */

#ifndef _Included_com_yyty_hao_studyproject_jni_JniTest
#define _Included_com_yyty_hao_studyproject_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yyty_hao_studyproject_jni_JniTest
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yyty_hao_studyproject_jni_JniTest_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
